[build]
  publish = "public"
  command = "npm install"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["replicate"]

[[redirects]]
  from = "/api/generate"
  to = "/.netlify/functions/generate"
  status = 200
